// Curated quick-reference summary of Magic: The Gathering's rules and keyword mechanics -
// NOT a reproduction of Wizards of the Coast's official Comprehensive Rules. Era groupings
// are approximate (by year range) rather than pinned to one exact set, since many mechanics
// spanned a whole block. Each top-level entry is one filterable, independently-rendered
// "rule set" section. Each entry's `bullets` are the actual gameplay rule (shown first,
// most prominent); `source` is the originating edition/year shown as a trailing note only -
// omit `source` for foundational rules that aren't tied to one release. Feel free to
// edit/expand this plain array directly.
var RULES_DATA = [
  {
    id: "basics",
    label: "Basic Rules",
    blurb: "The foundational structure every game of Magic runs on.",
    entries: [
      { term: "Game Zones", bullets: ["Library (deck), Hand, Battlefield, Graveyard, Stack, Exile, and Command are the zones a card can be in.", "Most zones are public information; your hand and library are not."] },
      { term: "Turn Structure", bullets: ["Beginning phase: untap, upkeep, draw.", "Main phase (first).", "Combat: beginning, declare attackers, declare blockers, damage, end.", "Main phase (second).", "End step, then cleanup."] },
      { term: "Priority & the Stack", bullets: ["Spells and abilities go on the stack and resolve last-in, first-out.", "Players pass priority in turn order.", "When everyone passes in succession, the top of the stack resolves."] },
      { term: "Casting Spells & Costs", bullets: ["Casting puts a spell on the stack, choosing targets/modes, and paying its costs (usually mana).", "Once cast, it can be responded to before it resolves."] },
      { term: "Mana & Colors", bullets: ["Five colors - White, Blue, Black, Red, Green - plus colorless.", "Lands and other sources produce mana, spent to pay costs.", "Unspent mana empties at the end of each step/phase."] },
      { term: "Combat", bullets: ["Attacking creatures are declared, then the defending player assigns blockers.", "Combat damage is dealt simultaneously, except first/double strike add an extra damage step."] },
      { term: "State-Based Actions", bullets: ["Checked continuously, without using the stack.", "Examples: a creature with lethal damage or 0 toughness dies; a player at 0 life loses."] },
      { term: "Winning & Losing", bullets: ["Most commonly: reduce all opponents to 0 life.", "Force an opponent to draw from an empty library.", "Or make them lose via a card effect (poison counters, alternate win conditions)."] },
      { term: "Card Types", bullets: ["Creature, Instant, Sorcery, Artifact, Enchantment, Planeswalker, Land, Battle, and Kindred (formerly Tribal).", "Each type follows its own timing rules for when it can be played."] },
    ],
  },
  {
    id: "evergreen",
    label: "Evergreen Keywords",
    blurb: "Core abilities reprinted in nearly every set, forming the game's baseline vocabulary.",
    // example: a real card (verified against Scryfall's API) that carries this keyword,
    // picked via `keyword:"X" type:creature order:edhrec` - not necessarily the single
    // most iconic printing of the ability, but a real, currently-relevant illustration
    // of what a card with it actually looks like. Image is Scryfall's deterministic CDN
    // path (https://cards.scryfall.io/{size}/front/{id[0]}/{id[1]}/{id}.jpg), so only the
    // id needs to be stored.
    entries: [
      { term: "Flying", bullets: ["Can only be blocked by creatures with flying or reach."], example: { id: "492c2f9a-51e7-4e0f-9899-23bf43ea988b", name: "Birds of Paradise" } },
      { term: "Reach", bullets: ["Can block creatures with flying.", "Doesn't grant flying itself."], example: { id: "f9246b68-580f-4f53-883d-7900880e4b0d", name: "Six" } },
      { term: "First Strike", bullets: ["Deals combat damage before creatures without first strike, in its own damage step."], example: { id: "f332cd21-46ed-4fff-9fd9-d5975bf0004d", name: "Knight of the White Orchid" } },
      { term: "Double Strike", bullets: ["Deals combat damage in both the first-strike and regular damage steps."], example: { id: "a747e6cf-c687-4c4f-8e07-d51165d6cb62", name: "Lizard Blades" } },
      { term: "Trample", bullets: ["Excess combat damage beyond what's needed to kill blockers carries over to the defending player or planeswalker."], example: { id: "84aa18de-6acc-46cc-8e28-3046790a6751", name: "Rampaging Baloths" } },
      { term: "Vigilance", bullets: ["Attacking doesn't cause this creature to tap."], example: { id: "3d6eacf2-f6c7-4ede-b5a5-7463602699ae", name: "Sun Titan" } },
      { term: "Haste", bullets: ["Can attack and use tap abilities the turn it enters the battlefield, ignoring summoning sickness."], example: { id: "276f5cee-a501-4658-bd4d-7a044bf1ccbc", name: "Craterhoof Behemoth" } },
      { term: "Lifelink", bullets: ["Damage this deals also gains its controller that much life."], example: { id: "49d0d7ec-4bee-47d3-91a6-43510be65402", name: "Mangara, the Diplomat" } },
      { term: "Deathtouch", bullets: ["Any amount of damage this deals to a creature is considered lethal."], example: { id: "be8439e6-f779-49f0-806a-b04995697a6a", name: "Baleful Strix" } },
      { term: "Menace", bullets: ["Can only be blocked by two or more creatures."], example: { id: "42acbf52-b137-44f0-a815-2817fe8d2da2", name: "Professional Face-Breaker" } },
      { term: "Defender", bullets: ["Can't attack."], example: { id: "018257cf-8981-4691-92ab-6a33f77c9680", name: "Crashing Drawbridge" } },
      { term: "Hexproof", bullets: ["Can't be the target of spells or abilities your opponents control."], example: { id: "2662837c-3837-4da9-80b4-79edb0b6c289", name: "Sylvan Caryatid" } },
      { term: "Indestructible", bullets: ["Isn't destroyed by lethal damage or 'destroy' effects.", "Can still be sacrificed, exiled, or have its toughness reduced to 0."], example: { id: "e82e61d1-488d-4627-a54c-d8496a967814", name: "Toski, Bearer of Secrets" } },
      { term: "Flash", bullets: ["Can be cast any time you could cast an instant, not just during your main phase with an empty stack."], example: { id: "881b6202-6d02-489b-b79c-62142c42ed1f", name: "Orcish Bowmasters" } },
      { term: "Ward", bullets: ["Whenever this becomes the target of a spell or ability an opponent controls, counter it unless they pay the ward cost."], example: { id: "32fd8b7c-baf3-4d3d-be6f-044a917b11a0", name: "Roaming Throne" } },
    ],
  },
  {
    id: "formats",
    label: "Game Types / Formats",
    blurb: "Different ways to play Magic - each defines its own deckbuilding rules and legal card pool.",
    entries: [
      { term: "Commander (EDH)", bullets: ["100-card singleton deck - no duplicate cards except basic lands.", "Built around one legendary creature (or eligible planeswalker) as your Commander.", "Every other card's color must fit within the Commander's color identity.", "Players start at 40 life instead of 20.", "21+ combat damage from a single Commander over the course of the game eliminates that player.", "Usually played multiplayer (3-4 players), with politics and table dynamics a big part of the format." ], source: "Grew from a casual format ('Elder Dragon Highlander'); later adopted and officially supported by Wizards of the Coast." },
      { term: "Standard", bullets: ["60-card minimum deck.", "Only cards from the most recently released sets are legal - a rotating pool, roughly the last ~2 years."] },
      { term: "Pioneer", bullets: ["60-card minimum deck.", "Legal card pool spans from Return to Ravnica (2012) forward.", "Non-rotating."] },
      { term: "Modern", bullets: ["60-card minimum deck.", "Legal card pool spans from the Modern-era border change (around 2003) forward.", "Non-rotating."] },
      { term: "Legacy", bullets: ["60-card minimum deck.", "Nearly the entire card pool is legal (Alpha onward), governed by a banned list.", "High power level; fast, consistent decks."] },
      { term: "Vintage", bullets: ["60-card minimum deck.", "The full card pool is legal.", "Extremely powerful cards are 'restricted' to a single copy instead of outright banned."] },
      { term: "Pauper", bullets: ["60-card minimum deck.", "Only cards that have been printed at common rarity (at any point) are legal."] },
      { term: "Draft / Limited", bullets: ["Players open booster packs and pick cards one at a time, passing the rest around the table.", "You build a deck (commonly a 40-card minimum) from only what you picked.", "Emphasizes evaluating and adapting to whatever you open, rather than a preconstructed deck."] },
      { term: "Sealed Deck", bullets: ["Each player opens a fixed number of booster packs (commonly six) and builds a deck using only those cards.", "40-card minimum, no picking/passing between players."] },
      { term: "Two-Headed Giant", bullets: ["Team format: two players share one 30-life pool and take turns together against another two-player team.", "Either teammate may cast spells/take actions during the team's shared turn.", "Either player on a team can be attacked or targeted."] },
      { term: "Brawl", bullets: ["Commander-style singleton format, but with a 60-card deck instead of 100.", "One legendary Commander restricts the deck's colors to its color identity, same as Commander.", "Players typically start at 25 life instead of Commander's 40."] },
    ],
  },
  {
    id: "tokens",
    label: "Special Token Types",
    blurb: "Named token types with their own defined rules text, usually created by an effect and later sacrificed for value.",
    entries: [
      { term: "Clue", bullets: ["Artifact token.", "{2}, Sacrifice this artifact: Draw a card."], source: "Created by the 'investigate' ability, Shadows over Innistrad (2016)." },
      { term: "Treasure", bullets: ["Artifact token.", "{T}, Sacrifice this artifact: Add one mana of any color."], source: "Kaladesh (2016); now a very common fixing/ramp token." },
      { term: "Food", bullets: ["Artifact token.", "{2}, {T}, Sacrifice this artifact: You gain 3 life."], source: "Throne of Eldraine (2019)." },
      { term: "Blood", bullets: ["Artifact token.", "{1}, {T}, Sacrifice this artifact, Discard a card: Draw a card."], source: "Innistrad: Midnight Hunt (2021)." },
      { term: "Powerstone", bullets: ["Artifact token.", "Taps for one mana, but that mana can only be spent to cast artifact spells or activate artifact abilities."], source: "The Brothers' War (2022)." },
      { term: "Map", bullets: ["Artifact token (equipment-like).", "{1}, {T}, Sacrifice this artifact: Target creature you control explores."], source: "Bloomburrow (2024)." },
      { term: "Incubator", bullets: ["Artifact token that enters with oil counters.", "{2}: Transform it into an X/X colorless Phyrexian creature, X equal to its oil counters."], source: "Phyrexia: All Will Be One (2023)." },
      { term: "Gold", bullets: ["Artifact token.", "Sacrifice this artifact: Add one mana of any color (no tap needed)."], source: "An older, simpler precursor to Treasure seen in some earlier sets." },
    ],
  },
  {
    id: "global-mechanics",
    label: "Global & Player-State Mechanics",
    blurb: "Rules that track a special game- or player-wide state, rather than a simple keyword printed on one card.",
    entries: [
      { term: "Day / Night", bullets: ["The game starts as neither day nor night.", "It becomes Night if no spells were cast the previous turn.", "It becomes Day if a player casts their second spell in a turn.", "Many cards have different effects, or only function, by day or by night."], source: "Innistrad: Midnight Hunt / Crimson Vow (2021) - not to be confused with Innistrad: Double Feature, a later (2023) black-and-white cosmetic reprint of the original Innistrad set that doesn't itself add new rules." },
      { term: "Monarch", bullets: ["One player is 'the Monarch.'", "The Monarch draws an extra card during their end step.", "Dealing combat damage to the Monarch makes you the new Monarch instead."], source: "Conspiracy: Take the Crown (2016); later a recurring Commander-product mechanic." },
      { term: "The Initiative / Undercity", bullets: ["Whoever 'takes the initiative' holds it and ventures into the Undercity at the start of their precombat main phase.", "Dealing combat damage to the holder passes the initiative to you instead."], source: "Lost Caverns of Ixalan (2023); similar in spirit to Monarch." },
      { term: "The Ring Tempts You", bullets: ["The Ring-bearer accumulates one-time 'temptations' over the course of the game.", "Each temptation grants a permanent bonus the first time it triggers, in a fixed order."], source: "The Lord of the Rings: Tales of Middle-earth (2023)." },
      { term: "Saga (enchantment subtype)", bullets: ["Enters with a lore counter, then gains another each of your precombat main phases (or as stated).", "Each lore-counter total triggers a chapter ability (I, II, III...) in sequence.", "Usually sacrificed after its final chapter resolves."], source: "Dominaria (2018)." },
      { term: "Class (enchantment subtype)", bullets: ["Enters at level 1.", "Pay a cost (sorcery speed) to level up.", "Higher levels unlock stronger printed abilities."], source: "Adventures in the Forgotten Realms (2021)." },
      { term: "Case (enchantment subtype)", bullets: ["Enters unsolved.", "Once its printed condition is met, it becomes solved, unlocking a bonus ability alongside its initial one."], source: "Murders at Karlov Manor (2024)." },
      { term: "Room (enchantment subtype)", bullets: ["Two linked 'door' halves printed on one card.", "You cast one door, then may unlock and cast the other later - functioning like two enchantments sharing a card."], source: "Duskmourn: House of Horror (2024)." },
      { term: "Background (Commander mechanic)", bullets: ["Legendary creatures with 'Choose a Background' can pair with a Background enchantment card.", "The Background acts as an extra, build-around commander component."], source: "Introduced alongside Commander Legends (2020)." },
      { term: "Partner (Commander mechanic)", bullets: ["Two legendary creatures that each have partner can be used together as your two commanders in Commander, instead of just one."] },
    ],
  },
  {
    id: "era-1993-1999",
    label: "1993–1999 · The Early Years",
    blurb: "Alpha through the Urza's Saga / Mercadian Masques era - Magic's first wave of non-evergreen mechanics.",
    entries: [
      { term: "Banding", bullets: ["A group of attacking (or blocking) creatures with banding can assign their combined combat damage among each other as their controller chooses.", "Complex and now rarely printed."] },
      { term: "Cumulative Upkeep", bullets: ["Each upkeep, add an age counter to this permanent.", "Then pay its cumulative upkeep cost once per age counter, or sacrifice it."] },
      { term: "Phasing", bullets: ["This permanent alternates between 'phased out' (treated as though it doesn't exist) and phased in.", "It flips state during each of its controller's untap steps."] },
      { term: "Echo", bullets: ["At the beginning of your first upkeep after this enters, pay its echo cost or sacrifice it."] },
      { term: "Buyback", bullets: ["Pay the buyback cost in addition to the spell's normal cost.", "If you do, it returns to your hand instead of the graveyard as it resolves."] },
      { term: "Flanking", bullets: ["Whenever this is blocked by a creature without flanking, that blocker gets -1/-1 until end of turn."] },
      { term: "Shadow", bullets: ["Can only block, or be blocked by, other creatures with shadow."] },
    ],
  },
  {
    id: "era-2000-2003",
    label: "2000–2003 · Invasion through Onslaught",
    blurb: "Multicolor themes and the debut of tribal/typal synergy support.",
    entries: [
      { term: "Kicker", bullets: ["You may pay an additional kicker cost as you cast this spell.", "If you do, you get an extra effect on top of the spell's normal one."] },
      { term: "Rebound", bullets: ["If this spell was cast from hand, exile it as it resolves instead of putting it in the graveyard.", "At the beginning of your next upkeep, cast it from exile for free."] },
      { term: "Morph", bullets: ["You may cast this face down as a 2/2 colorless creature with no text, paying {3} instead of its mana cost.", "Later, turn it face up by paying its morph cost."] },
      { term: "Threshold", bullets: ["This ability is only active while its controller has seven or more cards in their graveyard."] },
      { term: "Amplify", bullets: ["As this enters, reveal any number of creature cards of the named type from your hand.", "It enters with an extra +1/+1 counter for each card revealed this way."] },
    ],
  },
  {
    id: "era-2004-2007",
    label: "2004–2007 · Kamigawa, Ravnica & Time Spiral",
    blurb: "Legendary block-defining mechanics: Kamigawa's samurai/spirit themes, the ten Ravnica guilds, and Time Spiral's nostalgia trip.",
    entries: [
      { term: "Bushido", bullets: ["Whenever this creature blocks or becomes blocked, it gets +N/+N until end of turn."], source: "Kamigawa block (2004–2005)." },
      { term: "Ninjutsu", bullets: ["Return an unblocked attacking creature you control to hand.", "If you do, put this creature onto the battlefield from hand, attacking instead."], source: "Kamigawa block (2004–2005)." },
      { term: "Soulshift", bullets: ["When this Spirit creature dies, you may return a Spirit card with lesser mana value from your graveyard to your hand."], source: "Kamigawa block (2004–2005)." },
      { term: "Convoke", bullets: ["You may tap untapped creatures you control to help pay this spell's cost.", "Each creature tapped this way pays for {1} or one mana of that creature's color."], source: "Ravnica block (2005–2006)." },
      { term: "Dredge", bullets: ["Instead of drawing your card for the turn, you may mill cards equal to this card's dredge number.", "If you do, return this card from your graveyard to your hand instead."], source: "Ravnica block (2005–2006)." },
      { term: "Suspend", bullets: ["Exile this card from your hand, paying its suspend cost, and add the stated number of time counters.", "Remove a time counter at the beginning of each of your upkeeps.", "When the last is removed, cast it from exile for free."], source: "Time Spiral block (2006–2007)." },
      { term: "Splice onto Arcane", bullets: ["While casting an Arcane spell, you may reveal this card from your hand and pay its splice cost.", "If you do, add this card's effects to that spell without changing what it can target."], source: "Kamigawa block (2004–2005)." },
    ],
  },
  {
    id: "era-2008-2011",
    label: "2008–2011 · Shards of Alara through Innistrad",
    blurb: "Alara's shard color-pie identities, Zendikar's landfall-driven aggression, and the original Innistrad's graveyard/horror themes.",
    entries: [
      { term: "Landfall", bullets: ["Triggers whenever a land enters the battlefield under your control."], source: "Zendikar block (2009–2010)." },
      { term: "Level Up", bullets: ["Pay a cost to add a level counter to this creature.", "It gains better stats/abilities once its level counters reach specific thresholds."], source: "Rise of the Eldrazi (2010)." },
      { term: "Flashback (returning)", bullets: ["You may cast this card from your graveyard by paying its flashback cost.", "If you do, exile it instead of returning it to the graveyard afterward."], source: "Originally Odyssey (2001); returned in Innistrad (2011)." },
      { term: "Morbid", bullets: ["This ability is better, or only active, if a creature died this turn."], source: "Innistrad (2011)." },
      { term: "Undying", bullets: ["When this creature dies, if it had no +1/+1 counters on it, return it to the battlefield with a +1/+1 counter."], source: "Innistrad (2011)." },
      { term: "Transform / Double-Faced Cards", bullets: ["Some cards have two faces printed on one physical card.", "An effect flips the card between its front and back face instead of it being two separate cards."], source: "Innistrad (2011)." },
    ],
  },
  {
    id: "era-2012-2015",
    label: "2012–2015 · Return to Ravnica through Khans of Tarkir",
    blurb: "A second trip to the guilds, Theros's devotion-driven god cycle, and Khans's three-color wedge clans.",
    entries: [
      { term: "Scry (returning)", bullets: ["Look at the top N cards of your library.", "Put any number of them on the bottom of your library in any order, and the rest back on top in any order."], source: "Originally Future Sight (2007); prominent again from Theros block onward (2013–2014)." },
      { term: "Devotion", bullets: ["A count of the colored mana symbols among permanents you control.", "Cards like the Theros gods depend on reaching a devotion threshold to be creatures / stay indestructible."], source: "Theros block (2013–2014)." },
      { term: "Heroic", bullets: ["Triggers whenever you cast a spell that targets this creature."], source: "Theros block (2013–2014)." },
      { term: "Bestow", bullets: ["You may cast this card as an Aura for its bestow cost instead of casting it as a creature.", "If the enchanted creature leaves the battlefield, this becomes a creature itself."], source: "Theros block (2013–2014)." },
      { term: "Outlast", bullets: ["{Cost}, {T}: Put a +1/+1 counter on this creature.", "Activate only as a sorcery."], source: "Khans of Tarkir block (2014–2015)." },
      { term: "Delve", bullets: ["You may exile cards from your graveyard to help pay this spell's generic mana cost, one card per generic mana."], source: "Khans of Tarkir block (2014–2015)." },
      { term: "Manifest (returning as Morph variant)", bullets: ["Put the top card of your library onto the battlefield face down as a 2/2 creature.", "You may turn it face up later if it's a creature card, paying its mana cost."], source: "Khans of Tarkir block (2014–2015)." },
    ],
  },
  {
    id: "era-2016-2019",
    label: "2016–2019 · Kaladesh through War of the Spark",
    blurb: "Kaladesh's energy-driven artificers, Amonkhet's Egyptian-inspired trials, Ixalan's pirates/dinosaurs/vampires, and the climactic War of the Spark.",
    entries: [
      { term: "Energy", bullets: ["A colorless counter type ({E}) tracked on your player, not on any one card.", "Cards reference paying energy counters, or getting some."], source: "Kaladesh block (2016–2017)." },
      { term: "Fabricate", bullets: ["As this creature enters, either put N +1/+1 counters on it, or create N 1/1 Servo artifact creature tokens."], source: "Kaladesh block (2016–2017)." },
      { term: "Exert", bullets: ["You may exert this creature as it attacks for a bonus effect.", "If you do, it doesn't untap during your next untap step."], source: "Amonkhet block (2017)." },
      { term: "Explore", bullets: ["Reveal the top card of your library.", "Put it into your hand if it's a land; otherwise, put a +1/+1 counter on this creature and choose whether to keep the card on top or put it in the graveyard."], source: "Ixalan block (2017–2018)." },
      { term: "Ascend / The City's Blessing", bullets: ["Once you control 10 or more permanents, you get the city's blessing for the rest of the game.", "Cards that check for the city's blessing get a bonus effect once you have it."], source: "Ixalan block (2017–2018)." },
      { term: "Riot", bullets: ["This creature enters the battlefield with your choice of a +1/+1 counter, or haste."], source: "Guilds of Ravnica (2018)." },
      { term: "Amass", bullets: ["Create a 0/0 black Zombie Army creature token if you don't have one, then put the stated number of +1/+1 counters on it."], source: "War of the Spark (2019)." },
      { term: "Adventure", bullets: ["Cast the Adventure half of this card (an instant or sorcery) if you like.", "It goes to exile instead of the graveyard, and you may later cast the creature half from exile."], source: "Throne of Eldraine (2019)." },
    ],
  },
  {
    id: "era-2020-2022",
    label: "2020–2022 · Theros Beyond Death through The Brothers' War",
    blurb: "Constellation returns, Ikoria's monster mutations, Kaldheim's Norse sagas, and the Brothers' War's artifact-centric prototypes.",
    entries: [
      { term: "Mutate", bullets: ["Cast this creature card for its mutate cost, targeting a non-Human creature you control.", "It merges into one permanent with the target, as a stack of cards - the top card's name/face is normally used, but all abilities apply."], source: "Ikoria: Lair of Behemoths (2020)." },
      { term: "Companion", bullets: ["If your entire starting deck meets this card's companion restriction, you may put it in your sideboard instead of your deck.", "Pay {3} once per game to put it into your hand from the sideboard."], source: "Ikoria: Lair of Behemoths (2020)." },
      { term: "Foretell", bullets: ["Pay {2} and exile this card face down from your hand.", "On a later turn, cast it from exile for its (usually cheaper) foretell cost."], source: "Kaldheim (2021)." },
      { term: "Boast", bullets: ["Activate this ability only if this creature attacked this turn, and only once per turn."], source: "Kaldheim (2021)." },
      { term: "Disturb", bullets: ["Cast this card's back face from your graveyard for its disturb cost, instead of casting the front face."], source: "Innistrad: Midnight Hunt (2021)." },
      { term: "Casualty", bullets: ["As you cast this spell, you may sacrifice a creature with the stated power to copy the spell.", "The copy has any targets copied automatically."], source: "Streets of New Capenna (2022)." },
      { term: "Prototype", bullets: ["Cast this artifact for its listed alternative cost and size, or for its normal cost and size - your choice."], source: "The Brothers' War (2022)." },
    ],
  },
  {
    id: "era-2023-2025",
    label: "2023–2025 · Phyrexia through the present",
    blurb: "Phyrexian compleation, the Battle card type's debut, fairy-tale bargains, and outlaw heists.",
    entries: [
      { term: "Toxic", bullets: ["Combat damage dealt by this creature also gives that many poison counters to the player it damaged.", "A player with 10 or more poison counters loses the game."], source: "Phyrexia: All Will Be One (2023)." },
      { term: "Corrupted", bullets: ["This ability is better, or only active, if an opponent has three or more poison counters."], source: "Phyrexia: All Will Be One (2023)." },
      { term: "Battle Cards", bullets: ["A permanent card type with defense counters.", "Opponents can 'attack' a Battle like a planeswalker.", "When its defense counters hit zero, it's put into exile and (if double-faced) can flip to its back face."], source: "March of the Machine (2023)." },
      { term: "Bargain", bullets: ["You may sacrifice an artifact, enchantment, or token as you cast this spell.", "If you do, you get a bonus effect."], source: "Wilds of Eldraine (2023)." },
      { term: "Discover", bullets: ["Exile cards from the top of your library until you exile a nonland card with mana value N or less.", "Cast that card for free, or put it into your hand; put the rest on the bottom of your library in a random order."], source: "The Lost Caverns of Ixalan (2023)." },
      { term: "Plot", bullets: ["Exile this card from your hand for free during your turn.", "On a later turn, cast it from exile for free during your main phase."], source: "Outlaws of Thunder Junction (2024)." },
      { term: "Offspring", bullets: ["Pay an additional cost as you cast this creature.", "If you do, also create a smaller (usually 1/1, or half stats) copy token of it."], source: "Bloomburrow (2024)." },
      { term: "Backup", bullets: ["When this creature enters, put N +1/+1 counters on target creature.", "If that target isn't this creature, it also gains this creature's abilities until end of turn."], source: "March of the Machine (2023)." },
    ],
  },
];
