// Curated quick-reference summary of Magic: The Gathering's rules and keyword mechanics -
// NOT a reproduction of Wizards of the Coast's official Comprehensive Rules. Era groupings
// are approximate (by year range) rather than pinned to one exact set, since many mechanics
// spanned a whole block. Each top-level entry is one filterable, independently-rendered
// "rule set" section. Feel free to edit/expand this plain array directly.
var RULES_DATA = [
  {
    id: "basics",
    label: "Basic Rules",
    blurb: "The foundational structure every game of Magic runs on.",
    entries: [
      { term: "Game Zones", description: "Library (deck), Hand, Battlefield, Graveyard, Stack, Exile, and Command are the zones cards move between. Most zones are public information except your hand and library." },
      { term: "Turn Structure", description: "Beginning (untap, upkeep, draw) → Main Phase → Combat (beginning, declare attackers, declare blockers, damage, end) → Second Main Phase → End Step → Cleanup." },
      { term: "Priority & the Stack", description: "Spells and abilities go on the stack and resolve last-in-first-out. Players pass priority in turn order; when everyone passes in succession, the top of the stack resolves." },
      { term: "Casting Spells & Costs", description: "Casting a spell means putting it on the stack, choosing targets/modes, and paying its costs (usually mana). Once cast, it can be responded to before it resolves." },
      { term: "Mana & Colors", description: "Five colors - White, Blue, Black, Red, Green - plus colorless. Lands and other mana sources produce mana, which is spent to pay costs and empties at the end of each step/phase if unused." },
      { term: "Combat", description: "Attacking creatures are declared, defending player assigns blockers, then combat damage is dealt simultaneously (except first/double strike, which adds an extra damage step)." },
      { term: "State-Based Actions", description: "Checked continuously without using the stack: creatures with lethal damage or 0 toughness die, players at 0 life lose, etc." },
      { term: "Winning & Losing", description: "Most commonly: reduce all opponents to 0 life, force them to draw from an empty library, or make them lose via a card effect (e.g. poison counters, alternate win conditions)." },
      { term: "Card Types", description: "Creature, Instant, Sorcery, Artifact, Enchantment, Planeswalker, Land, Battle, and Kindred (formerly Tribal) each follow their own timing and rules for when they can be played." },
    ],
  },
  {
    id: "evergreen",
    label: "Evergreen Keywords",
    blurb: "Core abilities reprinted in nearly every set, forming the game's baseline vocabulary.",
    entries: [
      { term: "Flying", description: "Can only be blocked by creatures with flying or reach." },
      { term: "Reach", description: "Can block creatures with flying (but doesn't grant flying itself)." },
      { term: "First Strike", description: "Deals combat damage before creatures without first strike." },
      { term: "Double Strike", description: "Deals combat damage in both the first-strike and regular damage steps." },
      { term: "Trample", description: "Excess combat damage beyond what's needed to kill blockers carries over to the defending player/planeswalker." },
      { term: "Vigilance", description: "Attacking doesn't cause this creature to tap." },
      { term: "Haste", description: "Can attack and use tap abilities the turn it enters the battlefield." },
      { term: "Lifelink", description: "Damage this deals also gains its controller that much life." },
      { term: "Deathtouch", description: "Any amount of damage this deals to a creature is considered lethal." },
      { term: "Menace", description: "Can only be blocked by two or more creatures." },
      { term: "Defender", description: "Can't attack." },
      { term: "Hexproof", description: "Can't be the target of spells or abilities your opponents control." },
      { term: "Indestructible", description: "Isn't destroyed by lethal damage or 'destroy' effects (though it can still be sacrificed, exiled, etc.)." },
      { term: "Flash", description: "Can be cast any time you could cast an instant, not just during your main phase with an empty stack." },
      { term: "Ward", description: "Whenever this becomes the target of a spell or ability an opponent controls, counter it unless they pay the ward cost." },
    ],
  },
  {
    id: "era-1993-1999",
    label: "1993–1999 · The Early Years",
    blurb: "Alpha through the Urza's Saga / Mercadian Masques era - Magic's first wave of non-evergreen mechanics.",
    entries: [
      { term: "Banding", description: "Complex, now-rare combat mechanic letting banded creatures assign/redirect combat damage as a group." },
      { term: "Cumulative Upkeep", description: "Each upkeep, add an age counter, then pay the cost once per counter or sacrifice the permanent." },
      { term: "Phasing", description: "The permanent alternates between 'phased out' (treated as though it doesn't exist) and phased in each of its controller's untap steps." },
      { term: "Echo", description: "At the beginning of your first upkeep after this enters, pay its echo cost or sacrifice it." },
      { term: "Buyback", description: "Pay the buyback cost in addition to the spell's cost to return it to your hand instead of the graveyard as it resolves." },
      { term: "Flanking", description: "Whenever this is blocked by a creature without flanking, that blocker gets -1/-1 until end of turn." },
      { term: "Shadow", description: "Can only block or be blocked by other creatures with shadow." },
    ],
  },
  {
    id: "era-2000-2003",
    label: "2000–2003 · Invasion through Onslaught",
    blurb: "Multicolor themes and the debut of tribal/typal synergy support.",
    entries: [
      { term: "Kicker", description: "You may pay an additional kicker cost as you cast this spell for an extra effect." },
      { term: "Rebound", description: "If this spell was cast from hand, exile it as it resolves; at the beginning of your next upkeep, cast it from exile for free." },
      { term: "Morph", description: "You may cast this face-down as a 2/2 colorless creature for {3}, then turn it face up by paying its morph cost." },
      { term: "Threshold", description: "This ability is active only while you have seven or more cards in your graveyard." },
      { term: "Amplify", description: "As this enters, reveal any number of creature cards of the named type from your hand; it enters with an extra +1/+1 counter for each." },
    ],
  },
  {
    id: "era-2004-2007",
    label: "2004–2007 · Kamigawa, Ravnica & Time Spiral",
    blurb: "Legendary block-defining mechanics: Kamigawa's samurai/spirit themes, the ten Ravnica guilds, and Time Spiral's nostalgia trip.",
    entries: [
      { term: "Bushido", description: "(Kamigawa) Whenever this blocks or becomes blocked, it gets +N/+N until end of turn." },
      { term: "Ninjutsu", description: "(Kamigawa) Return an unblocked attacker you control to hand to put this creature onto the battlefield attacking instead." },
      { term: "Soulshift", description: "(Kamigawa) When this Spirit dies, you may return a Spirit card with lesser mana value from your graveyard to hand." },
      { term: "Convoke", description: "(Ravnica) You may tap untapped creatures you control to help pay this spell's cost, contributing colors or generic mana." },
      { term: "Dredge", description: "(Ravnica) Instead of drawing, you may mill cards equal to this card's dredge number to return it from graveyard to hand." },
      { term: "Suspend", description: "(Time Spiral) Exile this from hand paying its suspend cost, adding time counters; remove one each upkeep, then cast it free when the last is removed." },
      { term: "Splice onto Arcane", description: "(Kamigawa) While casting an Arcane spell, you may reveal this from hand and pay its splice cost to add its effects." },
    ],
  },
  {
    id: "era-2008-2011",
    label: "2008–2011 · Shards of Alara through Innistrad",
    blurb: "Alara's shard color-pie identities, Zendikar's landfall-driven aggression, and the original Innistrad's graveyard/horror themes.",
    entries: [
      { term: "Landfall", description: "(Zendikar) Triggers whenever a land enters the battlefield under your control." },
      { term: "Level Up", description: "(Rise of the Eldrazi) Pay a cost to add a level counter, granting better stats/abilities at higher level thresholds." },
      { term: "Flashback (returning)", description: "(Innistrad) Cast this from your graveyard by paying its flashback cost, then exile it instead of returning it to the graveyard." },
      { term: "Morbid", description: "(Innistrad) This ability is better/active if a creature died this turn." },
      { term: "Undying", description: "(Innistrad) When this dies, if it had no +1/+1 counters, return it to the battlefield with a +1/+1 counter." },
      { term: "Transform / Double-Faced Cards", description: "(Innistrad) Some cards have two faces printed on one card and flip between them via an effect, rather than being two separate cards." },
    ],
  },
  {
    id: "era-2012-2015",
    label: "2012–2015 · Return to Ravnica through Khans of Tarkir",
    blurb: "A second trip to the guilds, Theros's devotion-driven god cycle, and Khans's three-color wedge clans.",
    entries: [
      { term: "Scry (returning as evergreen-ish)", description: "(Theros era) Look at the top N cards of your library, then put any number on the bottom and the rest back in any order." },
      { term: "Devotion", description: "(Theros) A count of the colored mana symbols among permanents you control - your gods' indestructibility/creature status depends on hitting a devotion threshold." },
      { term: "Heroic", description: "(Theros) Triggers whenever you cast a spell that targets this creature." },
      { term: "Bestow", description: "(Theros) Cast this as an Aura for its bestow cost instead of as a creature; if the enchanted creature leaves, this becomes a creature itself." },
      { term: "Outlast", description: "(Khans of Tarkir) Tap, pay cost (only as a sorcery) to put a +1/+1 counter on this creature." },
      { term: "Delve", description: "(Khans of Tarkir) You may exile cards from your graveyard to help pay this spell's generic mana cost." },
      { term: "Morph / Manifest (returning)", description: "(Khans of Tarkir) Manifest puts the top library card face down as a 2/2, turnable face up later if it's a creature card." },
    ],
  },
  {
    id: "era-2016-2019",
    label: "2016–2019 · Kaladesh through War of the Spark",
    blurb: "Kaladesh's energy-driven artificers, Amonkhet's Egyptian-inspired trials, Ixalan's pirates/dinosaurs/vampires, and the climactic War of the Spark.",
    entries: [
      { term: "Energy", description: "(Kaladesh) A colorless counter type ({E}) stored on your player, spent by cards that reference paying or getting energy counters." },
      { term: "Fabricate", description: "(Kaladesh) As this enters, put N +1/+1 counters on it, or create that many 1/1 servo tokens." },
      { term: "Exert", description: "(Amonkhet) You may exert this creature as it attacks for a bonus effect; if you do, it doesn't untap during your next untap step." },
      { term: "Explore", description: "(Ixalan) Reveal the top card of your library; put it in hand if it's a land, otherwise put a +1/+1 counter on this creature and choose to keep or graveyard the card." },
      { term: "Ascend / The City's Blessing", description: "(Ixalan) Once you control 10+ permanents, you get the city's blessing permanently, unlocking bonus effects on cards that check for it." },
      { term: "Riot", description: "(Guilds of Ravnica) This creature enters with a +1/+1 counter or with haste, your choice." },
      { term: "Amass", description: "(War of the Spark) Create or add +1/+1 counters to an Army creature token you control." },
    ],
  },
  {
    id: "era-2020-2022",
    label: "2020–2022 · Theros Beyond Death through The Brothers' War",
    blurb: "Constellation returns, Ikoria's monster mutations, Kaldheim's Norse sagas, and the Brothers' War's artifact-centric prototypes.",
    entries: [
      { term: "Mutate", description: "(Ikoria) Cast this creature card for its mutate cost onto a non-Human creature you control, merging into one permanent with a stack of cards." },
      { term: "Companion", description: "(Ikoria) If your entire starting deck meets this card's companion restriction, you may put it in your sideboard and pay {3} once per game to put it into your hand." },
      { term: "Foretell", description: "(Kaldheim) Pay {2} and exile this face down from hand; later cast it for its (usually cheaper) foretell cost." },
      { term: "Boast", description: "(Kaldheim) Activate only if this creature attacked this turn, once per turn." },
      { term: "Disturb", description: "(Midnight Hunt) Cast this card's back face from your graveyard for its disturb cost." },
      { term: "Casualty", description: "(Streets of New Capenna) Sacrifice a creature with the given power to copy this spell." },
      { term: "Prototype", description: "(The Brothers' War) Cast this artifact for an alternative, smaller cost/size, or its normal cost/size." },
    ],
  },
  {
    id: "era-2023-2025",
    label: "2023–2025 · Phyrexia through the present",
    blurb: "Phyrexian compleation, the Battle card type's debut, fairy-tale bargains, and outlaw heists.",
    entries: [
      { term: "Toxic", description: "(Phyrexia: All Will Be One) Combat damage from this creature also gives that many poison counters (10 poison counters = you lose)." },
      { term: "Corrupted", description: "(Phyrexia: All Will Be One) This ability is better/active if an opponent has three or more poison counters." },
      { term: "Battle Cards", description: "(March of the Machine) A new permanent card type with defense counters; attacked like a planeswalker, and can flip to its back face when defense hits zero." },
      { term: "Bargain", description: "(Wilds of Eldraine) You may sacrifice an artifact, enchantment, or token as you cast this spell for a bonus effect." },
      { term: "Discover", description: "(Lost Caverns of Ixalan) Exile cards from the top of your library until you hit a nonland card with mana value N or less, then cast it free or put it in hand." },
      { term: "Plot", description: "(Outlaws of Thunder Junction) Exile this from hand for free during your turn; cast it free from exile on a later turn during your main phase." },
      { term: "Offspring", description: "(Bloomburrow) Pay an additional cost as you cast this creature to also create a smaller 1/1 (or half-stats) copy token." },
    ],
  },
];
